[package]
name = "matrix-appservice-rs"
description = "A library to aid in creating Matrix appservices."
version = "0.1.0"
license = "MIT"
repository = "https://github.com/lieuwex/matrix-appservice-rs/"
authors = ["Lieuwe Rooijakkers <lieuwerooijakkers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruma = { git = "https://github.com/ruma/ruma", features = [ "client-api" ], rev = "e843ccdb9064b9b753da5b839363b3ebb371f383" }
ruma-client = { git = "https://github.com/ruma/ruma", rev = "e843ccdb9064b9b753da5b839363b3ebb371f383" }

serde = "1"
serde_json = "1"
serde_yaml = "0.8"

hyper = { version = "0.14", features = ["server"] }
bytes = "1"

rand = "0.8"
