[package]
name = "matrix-appservice-rs"
version = "0.1.0"
authors = ["Lieuwe Rooijakkers <lieuwerooijakkers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruma = { git = "https://github.com/ruma/ruma", features = [ "ruma-events", "ruma-api" ] }
ruma-client = { git = "https://github.com/ruma/ruma" }

serde = "^1.0"
serde_json = "^1.0"
serde_yaml = "^0.8"

hyper = "0.13"
bytes = "0.5"

url = "2.1.1"

rand = "0.7.3"
