[package]
name = "matrix-appservice-rs"
description = "A library to aid in creating Matrix appservices."
version = "0.1.0"
license = "MIT"
repository = "https://github.com/lieuwex/matrix-appservice-rs/"
authors = ["Lieuwe Rooijakkers <lieuwerooijakkers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruma = { git = "https://github.com/ruma/ruma", rev = "219cea9c1e45f1507c32ddf2c39cc9e3c8914c96", features = [ "client-api" ] }
ruma-client = { git = "https://github.com/ruma/ruma", rev = "219cea9c1e45f1507c32ddf2c39cc9e3c8914c96" }

serde = "^1.0"
serde_json = "^1.0"
serde_yaml = "^0.8"

hyper = "0.13"
bytes = "0.5"

rand = "0.7.3"
